test_suites:
    - name: e2e
      script_path: /root/okta/samples-js-angular/scripts
      sort_order: '1'
      timeout: '10'
      script_name: e2e
      criteria: OPTIONAL
      queue_name: small

    - name: e2e-oie
      script_path: /root/okta/samples-js-angular/scripts
      sort_order: '1'
      timeout: '10'
      script_name: e2e-oie
      criteria: OPTIONAL
      queue_name: small

    - name: semgrep
      script_path: /root/okta/samples-js-angular/scripts
      sort_order: '3'
      timeout: '10'
      script_name: semgrep
      criteria: MERGE
      queue_name: small