test_suites:
    - name: e2e
      script_path: /root/okta/samples-js-angular/scripts
      sort_order: '1'
      timeout: '10'
      script_name: e2e
      criteria: MERGE
      queue_name: ci-queue-productionJenga-AL2023

    - name: e2e-oie
      script_path: /root/okta/samples-js-angular/scripts
      sort_order: '1'
      timeout: '10'
      script_name: e2e-oie
      criteria: MERGE
      queue_name: ci-queue-productionJenga-AL2023

    - name: semgrep
      script_path: /root/okta/samples-js-angular/scripts
      sort_order: '3'
      timeout: '10'
      script_name: semgrep
      criteria: MERGE
      queue_name: ci-queue-productionJenga-AL2023

    - name: snyk
      script_path: /root/okta/samples-js-angular/scripts
      script_name: snyk
      sort_order: '3'
      timeout: '200'
      criteria: MAINLINE
      queue_name: ci-queue-productionJenga-AL2023
      trigger: AUTO